### ISSUE TITLE
Minefold API features

### ISSUE THREAD

**Issue by chrislloyd** [aaronsalmon/minefold-menu-bar#1]
Hey! Firstly, this is amazeballs. I don't really have any issues but I was just wandering what sort of data you guys were wanting to put here? A list of servers or a list of online friends perhaps?

**Comment by aaronsalmon** [comment]
=) this is going to be great. All I want is this to ping the API (https://minefold.com/servers/52147.json) and have the menubar icon light up if someone is online. You will be able to drop it down to see a list of people online.
